#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root to see all listening ports."
    exit 1
fi
##shows listening sockets and  shows the PID and name of the program to which each socket belongs
echo "Listing all listening ports with corresponding PID and program name:"
echo "---------------------------------------------------------------"
netstat -tulnp | grep LISTEN
