#!/usr/bin/env bash

# Check if an IP address was provided as an argument
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Assign the IP address argument to a variable
IP_ADDRESS=$1

# Ping the IP address 5 times
echo "Pinging $IP_ADDRESS 5 times..."
ping -c 5 "$IP_ADDRESS"

